server:
  port: "${SERVER_PORT}"
spring:
  application:
    name: "ms_autenticacion_crediya"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  flyway:
    enabled: true
    baseline-on-migrate: true
    url: "jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}?serverTimezone=America/Bogota&useSSL=false&allowPublicKeyRetrieval=true"
    user: "${adapters.r2dbc.username}"
    password: "${adapters.r2dbc.password}"
    locations: "classpath:db/migration"
    connect-retries: 3
    placeholders:
      db: "${adapters.r2dbc.database}"
adapters:
  r2dbc:
    host: "${MYSQL_HOST:localhost}"
    port: "${MYSQL_PORT:3306}"
    database: "${MYSQL_DATABASE}"
    username: "${MYSQL_USER}"
    password: "${MYSQL_ROOT_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8002,http://ms_solicitudes:8002"
logging:
  level:
    root: "INFO"
    org.springframework.web: "ERROR"
    com.co.crediya.api: "DEBUG"
springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    path: "/swagger-ui.html"
    operationsSorter: "method"
    tagsSorter: "alpha"
    display-request-duration: true
    doc-expansion: "none"
    filter: true
jwt:
  secret: "${JWT_SECRET}"
  expiration: "${JWT_EXPIRATION}"